homework4
KornilovMikhail/androidHomework pull request #4
Opened 2018-10-07 21:17 UTC by KornilovMikhail

2018-10-07 21:22 UTC, NailShaykhrazievItis requested changes

2018-10-07 21:22 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/homework/MainActivity.java
> +}
в конце класса пустая строка

2018-10-07 21:22 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/homework/PlanetAdapter.java
> +        callback = (Callback) parent.getContext();
лучше в конструкторе передать колбек, тебе сейчас повезло что контекст равен активити

2018-10-07 21:22 UTC, Jaskelai commented
![screenshot_20181008-001958](https://user-images.githubusercontent.com/31703085/46587084-2b93ad80-ca90-11e8-95cd-05be1ce27b6b.jpg)
![screenshot_20181008-002007](https://user-images.githubusercontent.com/31703085/46587086-31898e80-ca90-11e8-84e9-4ac6abdd2498.jpg)

2018-10-07 22:02 UTC, KornilovMikhail commented
![screenshot_20181008-005945](https://user-images.githubusercontent.com/31703085/46587488-d35faa00-ca95-11e8-9cd2-e83732b4b265.jpg)

2018-10-08 09:12 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/homework/PlanetAdapter.java
>      public class PlanetHolder extends RecyclerView.ViewHolder {
у тебя колбек лежит в другом классе. Конструктор тоже должен быть в адаптере, а не плейсхолдере. и передавать нужно инстанс коллбека, а не инстанс контекста

2018-10-08 12:14 UTC, NailShaykhrazievItis approved these changes

2018-10-08 12:17 UTC, closed without merging